"""drop user trust columns

Revision ID: p8r0t2v4x6z8
Revises: o7q9s1u3w5y7
Create Date: 2026-08-10 12:00:00.000000

Drop the admin-curated trust mark (``users.is_trusted`` + ``users.trust_reason``).
Per-event attestation and moderation carry the quality signal, so no column
replaces these and no index existed on either (checked against the live schema:
``users`` carries only the pkey, the two uniques, ``ix_users_demo``,
``ix_users_live`` and ``ix_users_search_fts``, none of which reference them).

Hand-written, not autogenerated: several production indexes exist only in
migration files, and autogenerate would emit drops for them.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "p8r0t2v4x6z8"
down_revision: Union[str, None] = "o7q9s1u3w5y7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_column("users", "trust_reason")
    op.drop_column("users", "is_trusted")


def downgrade() -> None:
    op.add_column(
        "users",
        sa.Column("is_trusted", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column("users", sa.Column("trust_reason", sa.Text(), nullable=True))
