// GENERATED by gen-clips-manifest.js from public/clips/. Do not edit.
// Re-run `node gen-clips-manifest.js` after re-recording or after adding
// a drop-in capture (bot-x-capture.mp4 / x-export-capture.mp4).

export type RecordedClip = {
  src: string;
  fps: number;
  durationSec: number;
  marks: Record<string, number>;
};

export type DropInClip = {
  src: string;
  fps: number;
  durationSec: number;
  width: number;
  height: number;
};

export const RECORDED: Record<string, RecordedClip> = {
  "demo": {
    "src": "clips/demo.mp4",
    "fps": 60,
    "durationSec": 116.118,
    "marks": {
      "dezoom": 1.159,
      "rezoom": 4.471,
      "pan": 7.376,
      "pinHover": 9.755,
      "pinApproach": 11.628,
      "panelOpen": 13.313,
      "panelScroll": 14.915,
      "navSubmit": 18.139,
      "modeClick": 20.57,
      "scrollGuide": 23.164,
      "finderOpen": 25.386,
      "finderPick": 28.839,
      "filePicked": 30.285,
      "importClick": 32.668,
      "scanVisible": 37.957,
      "queueRedirect": 70.871,
      "draftApproach": 74.468,
      "draftOpen": 77.691,
      "conflictFocus": 79.491,
      "conflictPick": 82.819,
      "capturePick": 85.404,
      "reviewScroll": 86.78,
      "submit": 90.953,
      "published": 93.933,
      "mapReturn": 95.774,
      "authorOpen": 100.583,
      "authorType": 102.004,
      "authorPick": 104.11,
      "filtersClose": 106.672,
      "workEase": 108.116,
      "detectedApproach": 111.298,
      "detectedOpen": 112.299
    }
  },
  "bot-embed": {
    "src": "clips/bot-embed.mp4",
    "fps": 60,
    "durationSec": 9.379,
    "marks": {
      "embedX": 84,
      "embedY": 10,
      "embedW": 316.8,
      "embedH": 699.84
    }
  },
  "portfolio": {
    "src": "clips/portfolio.mp4",
    "fps": 60,
    "durationSec": 23.454,
    "marks": {
      "identity": 0,
      "work": 2.483,
      "coverage": 6.15,
      "submissions": 8.857,
      "cardClick": 11.029,
      "eventUrl": 12.372,
      "eventOpen": 12.457,
      "eventScroll": 13.358,
      "mapNav": 17.228,
      "mapUrl": 17.985,
      "mapOpen": 19.646
    }
  },
  "import-review": {
    "src": "clips/import-review.mp4",
    "fps": 60,
    "durationSec": 65.696,
    "marks": {
      "panel": 0,
      "finderOpen": 5.135,
      "finderPick": 8.611,
      "filePicked": 11.156,
      "importClick": 13.841,
      "privacyHold": 15.311,
      "importDone": 21.819,
      "queueOpen": 24.994,
      "filterReady": 27.595,
      "draftOpen": 34.873,
      "draftScroll": 36.873,
      "tagFill": 40.938,
      "submitClick": 50.548,
      "nextDraft": 52.682,
      "mapNav": 55.283,
      "mapOpen": 59.491,
      "mapEase": 60.691
    }
  }
};

export const DROP_INS: { botCapture: DropInClip | null; exportCapture: DropInClip | null } = {
  "botCapture": null,
  "exportCapture": null
};
