// GENERATED by gen-clips-manifest.js from public/clips/. Do not edit.
// Re-run `node gen-clips-manifest.js` after re-recording or after adding
// a drop-in capture (bot-x-capture.mp4 / x-export-capture.mp4).

export type RecordedClip = {
  src: string;
  fps: number;
  durationSec: number;
  marks: Record<string, number>;
};

export type DropInClip = {
  src: string;
  fps: number;
  durationSec: number;
  width: number;
  height: number;
};

export const RECORDED: Record<string, RecordedClip> = {
  "demo": {
    "src": "clips/demo.mp4",
    "fps": 60,
    "durationSec": 116.118,
    "marks": {
      "dezoom": 1.159,
      "rezoom": 4.471,
      "pan": 7.376,
      "pinHover": 9.755,
      "pinApproach": 11.628,
      "panelOpen": 13.313,
      "panelScroll": 14.915,
      "navSubmit": 18.139,
      "modeClick": 20.57,
      "scrollGuide": 23.164,
      "finderOpen": 25.386,
      "finderPick": 28.839,
      "filePicked": 30.285,
      "importClick": 32.668,
      "scanVisible": 37.957,
      "queueRedirect": 70.871,
      "detectionApproach": 74.468,
      "detectionOpen": 77.691,
      "conflictFocus": 79.491,
      "conflictPick": 82.819,
      "capturePick": 85.404,
      "reviewScroll": 86.78,
      "submit": 90.953,
      "published": 93.933,
      "mapReturn": 95.774,
      "authorOpen": 100.583,
      "authorType": 102.004,
      "authorPick": 104.11,
      "filtersClose": 106.672,
      "workEase": 108.116,
      "detectedApproach": 111.298,
      "detectedOpen": 112.299
    }
  },
  "bot-embed": {
    "src": "clips/bot-embed.mp4",
    "fps": 60,
    "durationSec": 9.379,
    "marks": {
      "embedX": 84,
      "embedY": 10,
      "embedW": 316.8,
      "embedH": 699.84
    }
  },
  "portfolio": {
    "src": "clips/portfolio.mp4",
    "fps": 60,
    "durationSec": 32.085,
    "marks": {
      "identity": 0,
      "coverage": 1.961,
      "insights": 7.364,
      "submissions": 14.199,
      "cardClick": 16.965,
      "eventUrl": 18.316,
      "eventOpen": 18.411,
      "eventScroll": 20.412,
      "archiveHover": 23.482,
      "mapNav": 25.841,
      "mapUrl": 26.6,
      "mapOpen": 28.272
    }
  },
  "import-review": {
    "src": "clips/import-review.mp4",
    "fps": 60,
    "durationSec": 72.954,
    "marks": {
      "panel": 0,
      "finderOpen": 3.643,
      "finderPick": 6.792,
      "filePicked": 7.372,
      "importClick": 9.756,
      "privacyHold": 11.232,
      "importDone": 33.768,
      "queueUrl": 37.303,
      "queueOpen": 37.396,
      "filterReady": 40.197,
      "draftUrl": 46.281,
      "draftOpen": 46.448,
      "draftScroll": 48.849,
      "tagFill": 52.216,
      "submitClick": 60.263,
      "nextDraft": 62.305,
      "mapNav": 64.705,
      "mapUrl": 65.605,
      "mapOpen": 67.526,
      "mapEase": 68.427
    }
  }
};

export const DROP_INS: { botCapture: DropInClip | null; exportCapture: DropInClip | null } = {
  "botCapture": null,
  "exportCapture": null
};
